### ISSUE TITLE
What does this package offer that Symfony VarDumper does not have?

### ISSUE THREAD

**Issue by yeroon** [Bonemeijer/SmartDump#3]
What does this package offer that Symfony VarDumper does not have?
![why](https://media1.tenor.com/images/21d4549b64051e4ad60cb58c95beb82c/tenor.gif?itemid=5952123)

**Comment by Bonemeijer** [comment]
Just a few small things for now, like
- detecting postman
- detecting HTTP Accept header
- detecting XHR requests
- dumping to a stream

But I have some more ideas which will make it a more distinguishable alternative.
